# Generated by Django 3.0.2 on 2020-02-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_auto_20200223_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='Username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
