# Generated by Django 3.0.2 on 2020-02-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_auto_20200223_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('RollNo', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('StdName', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
